wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.15
    t:
      1:
      - 1
      4: 3.6.15
      5: 0.10.22
      8:
      - 5
alpha:
  desc: null
  value:
  - 0.35
  - 0.35
  - 0.15
  - 0.15
aug:
  desc: null
  value: false
b0:
  desc: null
  value: 1000
b_size:
  desc: null
  value: 100
cuda:
  desc: null
  value: 0
f_conv:
  desc: null
  value: 5
f_lift:
  desc: null
  value: 1
gamma:
  desc: null
  value: 2.0
lr:
  desc: null
  value: 0.001
num_epoch:
  desc: null
  value: 100
num_shells:
  desc: null
  value: 1
ray_len:
  desc: null
  value: null
watson_param:
  desc: null
  value: 10
