wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.15
    t:
      1:
      - 1
      4: 3.6.15
      5: 0.10.22
      8:
      - 5
b0:
  desc: null
  value: 1000
b_size:
  desc: null
  value: 100
cuda:
  desc: null
  value: 0
f1:
  desc: null
  value: 90
f2:
  desc: null
  value: 5
f3:
  desc: null
  value: 5
f4:
  desc: null
  value: 5
num_epoch:
  desc: null
  value: 100
num_shells:
  desc: null
  value: 1
